name: Cross-Platform Test & Build

on:
  push:
    branches: [ "main" ]  # 当代码推送到 main 分支时触发
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-mac:
    # 运行在最新的 macOS 环境中（针对 Mac 用户群）
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # 自动缓存依赖，加快下次运行速度

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          # 运行测试脚本，确保语义检索内核 (Numpy) 在 Mac 下工作正常
          # 建议强手开发者写一些简单的测试用例
          python -m pytest tests/test_core.py

      - name: Attempt Build (Dry Run)
        run: |
          # 尝试在 Mac 下执行打包命令，确保没有路径或权限错误
          pyinstaller --onefile --noconsole main.py

  test-on-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m pytest tests/test_core.py

      - name: Attempt Build (Dry Run)
        run: |
          pyinstaller --onefile --noconsole main.py